name: Funny comments

on:
  pull_request:
  issues:
    types: [opened]
    
jobs:
  punny:
    runs-on: ubuntu-latest
    name: Reward PRs with a random pun
    steps:
    - uses: AlexLakatos/puns-dev-action@v1.3
      id: pun
    - uses: allthatjazzleo/actions-pull-request-add-comment@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: |
          Thank you for submitting a PR! Here's a pun, while you wait for us to review your PR.

          ${{ steps.pun.outputs.pun }}
          ${{ steps.pun.outputs.punchline }}
